url: https://jonghyeon99.github.io
baseurl: 
locale: 'ko-KR'
# Site settings
title: jonghyeon99 blog
email: your-email@domain.com
description: "jonghyeon99 blog's"


# Team names, titles and social links
people:
- name: Shin JiWon
  pic: 1
  position: Full-Stack Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: http://github.com/wldnjs0656

- name: Cho WonHong
  pic: 2
  position: Full-Stack Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: https://www.instagram.com/hong_cho_99/

- name: Yun EunBi
  pic: 3
  position: Full-Stack Developer
  social:
    - title: twitter
      url: #
    - title: instagram
      url: https://www.instagram.com/eung.__.bee/
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/trav.hyeon/
  - title: facebook
    url: https://www.facebook.com/people/%EC%8B%A0%EC%A2%85%ED%98%84/pfbid02XJs3zK3y5USWpwSbzgTuzMJJw73B5WuSAvgaoiCCEs9Lozi2j6AXNaW6jLPnY59tl/
  - title: github
    url: http://github.com/jonghyeon99

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty